name: first workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcom message
        run: echo "welcome to our firrst github action"

      - name: checkout repository
        uses: actions/checkout@v6.0.1

      - name: list files
        run: ls -la
        
